apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-kiali
  namespace: istio-system
spec:
  selector:
    istio: externalgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
        - kiali.${cluster_domain}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: kiali-${secret_name_suffix}
      hosts:
        - kiali.${cluster_domain}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-kiali
  namespace: istio-system
spec:
  hosts:
    - kiali.${cluster_domain}
  gateways:
    - istio-kiali
  http:
    - match:
      - uri:
          prefix: /
      route:
        - destination:
            port:
              number: 20001
            host: kiali

---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: istio-kiali
  namespace: istio-system
spec:
  secretName: kiali-${secret_name_suffix}
  issuerRef:
    name: ${cert_manager_default_cluster_issuer}
    kind: ClusterIssuer
  commonName: kiali.${cluster_domain}
  dnsNames:
    - kiali.${cluster_domain}
